// One-Pager Generation Prompt for Treaty Analysis

export function buildOnePagerPrompt(treatyText, treatyName = "Treaty") {
    return `You are an expert AI governance analyst. Create a concise, professional one-page briefing document from this treaty/policy document.

DOCUMENT NAME: ${treatyName}

DOCUMENT TEXT:
${treatyText.substring(0, 20000)}

---

Generate a structured one-page brief in MARKDOWN format with the following sections:

# ${treatyName} - Executive Brief

## 📋 Overview
[2-3 sentence summary of the document's purpose and scope]

## 🎯 Key Objectives
- [Objective 1]
- [Objective 2]
- [Objective 3]
(List 3-5 main objectives)

## ✅ Core Requirements
| Requirement | Description | Priority |
|-------------|-------------|----------|
| [Name] | [Brief description] | High/Medium/Low |
(Include 4-6 key requirements in table format)

## 🔍 Verification Needs
- **Compute Monitoring**: [Yes/No/Partial - brief explanation]
- **Model Lineage**: [Yes/No/Partial - brief explanation]  
- **Deployment Controls**: [Yes/No/Partial - brief explanation]
- **Post-Training Audits**: [Yes/No/Partial - brief explanation]

## 🛠️ Recommended Mechanisms
1. **[Mechanism Name]**: [Why it's recommended]
2. **[Mechanism Name]**: [Why it's recommended]
3. **[Mechanism Name]**: [Why it's recommended]

## ⚠️ Implementation Challenges
- [Challenge 1]
- [Challenge 2]
- [Challenge 3]

## 📊 Feasibility Assessment
| Dimension | Score (1-5) | Notes |
|-----------|-------------|-------|
| Technical Feasibility | [X] | [Brief note] |
| Political Tractability | [X] | [Brief note] |
| Sovereignty Impact | [X] | [Brief note] |
| Global South Adoptability | [X] | [Brief note] |

## 💡 Key Takeaways
1. [Main insight 1]
2. [Main insight 2]
3. [Main insight 3]

---
*Generated by VMFS Treaty Advisor*

---

IMPORTANT: 
- Keep the entire brief to roughly one page when printed
- Use clear, professional language suitable for policymakers
- Be specific and actionable in recommendations
- Base all assessments on the actual document content`;
}
