// One-Pager Generation Prompt for Treaty Analysis
// Updated with new 4-dimension scoring system

export function buildOnePagerPrompt(treatyText, treatyName = "Treaty") {
    return `You are the Verification Architect generating an executive brief for policymakers.

DOCUMENT NAME: ${treatyName}

DOCUMENT TEXT:
${treatyText.substring(0, 20000)}

---

Generate a structured one-page verification brief in MARKDOWN format:

# ${treatyName} - Verification Brief

## Overview
[2-3 sentence summary of the document's purpose and scope, focusing on verification needs]

## Key Verification Requirements
| Requirement | Evidence Location | Type |
|-------------|------------------|------|
| [Requirement 1] | [chip_hardware/data_center/institutional/etc.] | [Primary/Secondary] |
| [Requirement 2] | [...] | [...] |
| [Requirement 3] | [...] | [...] |
| [Requirement 4] | [...] | [...] |
(Include 4-6 key requirements mapped to evidence locations)

## Recommended Verification Mechanisms
Based on the document's requirements, recommend 3 mechanisms with their dimension scores:

1. **[Mechanism Name]**
   - Match Score: [X]%
   - Hardness: [X]/5 | Burden: [X]/5 | Intrusion: [X]/5 | Robustness: [X]/5
   - Rationale: [Why this mechanism fits the requirements]

2. **[Mechanism Name]**
   - Match Score: [X]%
   - Hardness: [X]/5 | Burden: [X]/5 | Intrusion: [X]/5 | Robustness: [X]/5
   - Rationale: [Why this mechanism fits]

3. **[Mechanism Name]**
   - Match Score: [X]%
   - Hardness: [X]/5 | Burden: [X]/5 | Intrusion: [X]/5 | Robustness: [X]/5
   - Rationale: [Why this mechanism fits]

## Portfolio Analysis
| Dimension | Score | Assessment |
|-----------|-------|------------|
| Evidence Hardness (Trust) | [X]/5 | [Is evidence physics-based or relies on honesty?] |
| Infrastructure Burden (Cost) | [X]/5 | [What must be built to implement?] |
| Intrusion Level (Friction) | [X]/5 | [How much IP/privacy is exposed?] |
| Evasion Robustness (Cheating) | [X]/5 | [How hard is it to bypass?] |

## Blind Spot Analysis
[Identify critical coverage gaps in the recommended portfolio]
- [ ] Chip-level verification: [Covered/NOT COVERED]
- [ ] Data center monitoring: [Covered/NOT COVERED]
- [ ] Institutional records: [Covered/NOT COVERED]
- [ ] Deployment controls: [Covered/NOT COVERED]

**Critical Warning:** [If any major blind spots exist, explain the risk]

## Implementation Priorities
1. **Immediate:** [What can be implemented with existing infrastructure]
2. **Near-term:** [What requires commercial cooperation]
3. **Long-term:** [What requires new hardware/infrastructure]

## Key Trade-offs
| Trade-off | Implication |
|-----------|-------------|
| Trust vs Cost | [Explanation] |
| Intrusion vs Robustness | [Explanation] |

---
*Generated by VMFS Verification Architect*

---

IMPORTANT GUIDELINES:
- Keep the brief to roughly one page when printed
- Use clear, professional language suitable for treaty negotiators
- Be specific about evidence locations and dimension scores
- Always identify blind spots and warn about coverage gaps
- Focus on actionable recommendations based on the document content
- Use the 4-dimension scoring system: Hardness, Burden, Intrusion, Robustness`;
}
